version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/fresh8/domsub
    steps:
      - checkout
      - run:
          name: "Go Build"
          command: |
            make -j2

workflows:
  version: 2
  build:
    jobs:
      - build
